[project]
name = "di-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "streamlit>=1.44.0",
    "uvicorn>=0.34.0",
]
